### ISSUE TITLE
create corresponding pool

### ISSUE THREAD

**Issue by Hr46ph** [qnap-dev/QNAP-CSI-PlugIn#10]
Unfortunately I don't quite understand all the steps, perhaps someone can clarify some things for me.

I was able to downgrade Kubernetes to 1.27.14, the latest in the 1.27 branch (if case you read my other question).

I got to this point:
```
$ tridentctl get storageclass -n trident
+------------+
|    NAME    |
+------------+
| qts-nasnas |
| premium    |
| standard   |
| basic      |
+------------+
$ tridentctl get backend -n trident
+------------+----------------+--------------------------------------+--------+---------+
|    NAME    | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------+----------------+--------------------------------------+--------+---------+
| qts-nasnas | qnap-iscsi     | 7f95b014-db12-43f4-9b07-23d72f485178 | online |       0 |
+------------+----------------+--------------------------------------+--------+---------+
```
On the NAS I have the following:
<img width="648" alt="image" src="https://github.com/qnap-dev/QNAP-CSI-PlugIn/assets/6275310/dc621079-c64d-43f2-8fbf-702f20c88af3">
The command from the instructions at "Installation" after the step to create the backend based on the yaml (which created the backend above) doesn't work:
```
kubectl get qpools -n trident
error: the server doesn't have a resource type "qpools"
```
When I check the resources available in the trident namespace I get (complete list):
```
apiservices.apiregistration.k8s.io                            networkpolicies.networking.k8s.io
certificatesigningrequests.certificates.k8s.io                nodes
ciliumcidrgroups.cilium.io                                    nodes.metrics.k8s.io
ciliumclusterwideenvoyconfigs.cilium.io                       persistentvolumeclaims
ciliumclusterwidenetworkpolicies.cilium.io                    persistentvolumes
ciliumendpoints.cilium.io                                     poddisruptionbudgets.policy
ciliumenvoyconfigs.cilium.io                                  pods
ciliumexternalworkloads.cilium.io                             pods.metrics.k8s.io
ciliumidentities.cilium.io                                    podtemplates
ciliuml2announcementpolicies.cilium.io                        priorityclasses.scheduling.k8s.io
ciliumloadbalancerippools.cilium.io                           prioritylevelconfigurations.flowcontrol.apiserver.k8s.io
ciliumnetworkpolicies.cilium.io                               replicasets.apps
ciliumnodeconfigs.cilium.io                                   replicationcontrollers
ciliumnodes.cilium.io                                         resourcequotas
ciliumpodippools.cilium.io                                    rolebindings.rbac.authorization.k8s.io
clusterrolebindings.rbac.authorization.k8s.io                 roles.rbac.authorization.k8s.io
clusterroles.rbac.authorization.k8s.io                        runtimeclasses.node.k8s.io
componentstatuses                                             secrets
configmaps                                                    serviceaccounts
controllerrevisions.apps                                      services
cronjobs.batch                                                statefulsets.apps
csidrivers.storage.k8s.io                                     storageclasses.storage.k8s.io
csinodes.storage.k8s.io                                       tridentbackendconfigs.trident.qnap.io
csistoragecapacities.storage.k8s.io                           tridentbackends.trident.qnap.io
customresourcedefinitions.apiextensions.k8s.io                tridentmirrorrelationships.trident.qnap.io
daemonsets.apps                                               tridentnodes.trident.qnap.io
deployments.apps                                              tridentorchestrators.trident.qnap.io
endpoints                                                     tridentsnapshotinfos.trident.qnap.io
endpointslices.discovery.k8s.io                               tridentsnapshots.trident.qnap.io
events                                                        tridentstorageclasses.trident.qnap.io
events.events.k8s.io                                          tridenttransactions.trident.qnap.io
flowschemas.flowcontrol.apiserver.k8s.io                      tridentversions.trident.qnap.io
horizontalpodautoscalers.autoscaling                          tridentvolumepublications.trident.qnap.io
ingressclasses.networking.k8s.io                              tridentvolumereferences.trident.qnap.io
ingresses.networking.k8s.io                                   tridentvolumes.trident.qnap.io
jobs.batch                                                    validatingwebhookconfigurations.admissionregistration.k8s.io
leases.coordination.k8s.io                                    volumeattachments.storage.k8s.io
limitranges                                                   volumesnapshotclasses.snapshot.storage.k8s.io
mutatingwebhookconfigurations.admissionregistration.k8s.io    volumesnapshotcontents.snapshot.storage.k8s.io
namespaces                                                    volumesnapshots.snapshot.storage.k8s.io
```

All resources in -n trident:
```
$ kubectl get all -n trident 
NAME                                     READY   STATUS    RESTARTS   AGE
pod/trident-controller-565b9b7bd-f89c9   6/6     Running   0          61m
pod/trident-node-linux-2bbfn             2/2     Running   0          61m
pod/trident-node-linux-8vpg4             2/2     Running   0          61m
pod/trident-node-linux-gg7l6             2/2     Running   0          61m
pod/trident-node-linux-sfqn8             2/2     Running   0          61m
pod/trident-node-linux-wflvv             2/2     Running   0          61m
pod/trident-operator-5c7554c44b-shczg    1/1     Running   0          62m

NAME                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)              AGE
service/trident-csi   ClusterIP   10.96.4.165   <none>        34571/TCP,9220/TCP   61m

NAME                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/trident-node-linux   5         5         5       5            5           <none>          61m

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/trident-controller   1/1     1            1           61m
deployment.apps/trident-operator     1/1     1            1           62m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/trident-controller-565b9b7bd   1         1         1       61m
replicaset.apps/trident-operator-5c7554c44b    1         1         1       62m
```
Here is the backend-config I used:
```
apiVersion: v1
kind: Secret
metadata:
  name: backend-qts-secret
  namespace: trident
type: Opaque
stringData:
  username: devkube
  password: bla
  storageAddress: nasnas.domain.net
---
apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qts-config
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-iscsi
  backendName: qts-nasnas
  networkInterfaces: ["Adapter 1+2"] #optional
  credentials:
    name: backend-qts-secret
  debugTraceFlags:
    method: false
  storage:
    - labels:
        storage: qts-nasnas
        serviceLevel: Any
    - labels:
        performance: premium
      features:
        tiering: Enable
        tierType: SSD
        ssdCache: "true"
      serviceLevel: SSD-Cache
    - labels:
        performance: standard
      features:
        tiering: Enable
      serviceLevel: Tiering
    - labels:
        performance: basic
      features:
        tiering: Disable
      serviceLevel: Non-Tiering
```
$ cat backend-sample.json 
```
{
    "version": 1,
    "storageDriverName": "qnap-iscsi",
    "backendName": "qts-nasnas",
    "storageAddress": "nasnas.dolmain.net",
    "username": "devkube",
    "password": "bla",
    "networkInterfaces": ["Adapter 1+2"], 
    "debugTraceFlags": {"method":true},
    "storage": [
        {
            "labels": {"storage": "qts-nasnas"},
            "serviceLevel": "Any"
        },
        {
            "labels": {"performance": "premium"},
            "features":{
                "tiering": "Enable",
                "ssdCache": "true"
            },
            "serviceLevel": "SSD-Cache"
        },
        {
            "labels": {"performance": "standard"},
            "features":{
                "tiering": "Enable"
            },
            "serviceLevel": "Tiering"
        },
        {
            "labels": {"performance": "basic"},
            "features":{
                "tiering": "Disable"
            },
            "serviceLevel": "Non-Tiering"
        }
    ]
}
```
$ cat sc.yaml 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=premium"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=standard"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=basic"
allowVolumeExpansion: true
```
$ cat sc_backend.yaml 
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qts-nasnas
provisioner: csi.trident.qnap.io
parameters:
  selector: "storage=qts-nasnas"
allowVolumeExpansion: true
```
$ cat pvc-standard.yaml 
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-standard
  annotations:
    # thin allocate is customized
    trident.qnap.io/ThinAllocate: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
```
The volume remains in a pending state.

Any help will be greatly appreciated!

Thanks!
