### ISSUE TITLE
Authentication issues, secrets, port changes, and base64 encoding

### ISSUE THREAD

**Issue by ckode** [qnap-dev/QNAP-CSI-PlugIn#34]
Hi,

I've been attempting to get this setup in my k3s / Rancher cluster and while I'm past the installation issue, I'm not getting authentication issues and also an inability to change the port for authentication to occur.

I have a couple of questions for clarification.

I noticed that the plugin automatically adds the port 8080 on the storageAddress.   II was able to change the 80 port to 8080, but was wondering if there was a way to change the port that the plugin uses or if it was hard coded?  I would also prefer it to use HTTPS if possible rather than an unencrypted HTTP connection.

Following the documentation, I setup a secret using Sealed Secrets for my cluster.   When I attempted to get it working, my QNAP was not receiving any auth requests and following internal kubectl describe and logs investigation, it was not able to connect.    Unsure about it, I checked my secrets and they seemed fine.  

In my home lab and my work, our Sealed Secrets must be base64 encoded before we encrypt them.   I had a feeling something was amiss and I resealed the storageAddress without first base64 it before encrypting it.    I immediately started seeing repeating authentication attempts from the plugin, but the username was random letters that I immediately recognized as the base64 encoded username.

This does not fit my experience with Kubernetes and leaves me to ask.  Am I missing something?  The installation documentation does not mention this.  My experience is mostly on k3s with Rancher and maybe that is implementation specific.

Finally, I re-sealed all my secrets without base64 encoding and I can see the authentication attempts, but it continues to fail and I'm at a loss to why and suspect there might be more things involved that are implementation specific.

The only other thought I had is that the Plugin complains that NetApp will not support using Trident with Kubernetes v1.32.5+k3s1,   Though when authenticating on the QNAP would seem to be beyond the context / scope of Trident and Kubernetes versioning since it reach the point of an authentication web request to the QNAP device at that point.

Thanks for any feedback / help you may provide.
~ ckode

**Comment by ckode** [comment]
Pre-sealing which I believe I just copied and pasted from this github page and updated the values.

`apiVersion: v1
kind: Secret
metadata:
  name: backend-qts-secret # Required. Name your secret.
  namespace: trident
type: Opaque
stringData:
  username: "[USER]" # Required. Your NAS username.
  password: "[PASSWORD]" # Required. Your NAS password.
  storageAddress: "[IP ADDRESS]"  # Required. Your NAS IP address.
`


The output after it was sealed. (minus the encrypted text)
`---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-qts-secret
  namespace: trident
spec:
  encryptedData:
    password: <encrypted>
    storageAddress: <encrypted>
    username:  <encrypted>
  template:
    metadata:
      creationTimestamp: null
      name: backend-qts-secret
      namespace: trident`

I use a script I created for sealing secrets, but the command it runs is as follows:

` kubeseal --controller-name sealed-secrets-controller --controller-namespace kube-system -f ~/secrets/${secret}.yaml -o yaml > ~/sealed_secrets/${secret}_sealed_secret.yaml`

I went back and removed the double quotes off of the yaml before I encrypted it, but that didn't work either.  Still see the users failing to login at over http-8080 in the QNAP.

Given it's HTTP, when I get a chance this evening. I will sniff the traffic and see exactly what it's sending to the QNAP on port 8080,

**Comment by ckode** [comment]
Sorry, I thought the code block would format better than that.  I realize that isn't readable YAML.

**Comment by ckode** [comment]
I'm gotten further, but now I'm getting an odd error where I create the StorageClass and it creates it, but I get an error saying it can't created it because it's being deleted.    But it's there.   

Then if I try to create the test volume, it says the StorageClass doesn't exist.  . ..even though it's there.

```
$ k get sc
NAME                   PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path             rancher.io/local-path                                      Delete          WaitForFirstConsumer   false                  8d
nfs-client (default)   cluster.local/nfs-client-nfs-subdir-external-provisioner   Delete          Immediate              true                   8d
qnap-ssd               csi.trident.qnap.io                                        Delete          Immediate              true                   15m

$ k describe sc qnap-ssd
Name:            qnap-ssd
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"qnap-ssd"},"parameters":{"fsType":"ext4","selector":"performance=ssd"},"provisioner":"csi.trident.qnap.io"}

Provisioner:           csi.trident.qnap.io
Parameters:            fsType=ext4,selector=performance=ssd
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

Now below I am cherry picking the errors.

The first error happens when I create the StorageClass above, but as you can see above.  The StorageClass is created.

The second error occurs where delete the StorageClass.  It deletes the storage class, but it says it can't because qnap-ssd doesn't exist. ?!?!!

When the StorageClass exists and I try to create the test PVC, I get the last error saying unknow storage class qnap-ssd.
```
$ tridentctl logs -n trident
 <snip>
time="2025-06-28T23:18:41Z" level=warning msg="K8S helper could not add a storage class: object is being deleted: tridentstorageclasses.trident.qnap.io \"qnap-ssd\" already exists" logLayer=csi_frontend name=qnap-ssd parameters="map[fsTy
pe:ext4 selector:performance=ssd]" provisioner=csi.trident.qnap.io requestID=fad4b8e8-25c6-4ec1-8c0c-419a51d93670 requestSource=Kubernetes workflow="storage_class=create"


time="2025-06-28T22:55:40Z" level=error msg="K8S helper could not delete the storage class: storage class qnap-ssd not found" logLayer=csi_frontend name=qnap-ssd requestID=2c14328e-5962-4b00-bef3-0a09eb3c496f requestSource=Kubernetes workflow="storage_class=delete"


time="2025-06-28T23:16:02Z" level=error msg="GRPC error: rpc error: code = Unknown desc = unknown storage class: qnap-ssd" logLayer=csi_frontend requestID=363dfbf9-d440-4127-82e1-9ad44c46f158 requestSource=CSI

```

So even though the storage class is there, for whatever reason it acts like it cannot see it.

**Comment by Shanna-chen** [comment]
Hi @ckode 
Thank you for your response. Regarding your questions, here are our responses:

1. Changing the Plugin Port: Currently, the QNAP CSI driver requires the use of port 8080 to communicate with the QNAP NAS, and it is not possible for users to customize this port. 
However, our team is carefully evaluating whether to allow port configuration in future releases. Please stay tuned for updates in upcoming versions.

2. StorageClass Abnormal Behavior: When you create a StorageClass, the system automatically generates a corresponding tridentstorageclass. To resolve the issue, please ensure that the tridentstorageclass is fully cleared. You can verify this by running:
`kubectl get tridentstorageclasses.trident.qnap.io -n trident`

Please let us know the results of the above command or share any relevant logs, and we’ll be happy to assist further!

**Comment by ckode** [comment]
Okay, I saw both qnap-splindle and qnap-ssd in this list.   I also saw some other items that remained even after deleting the trident namespace using the following command:

```
kubectl api-resources --verbs=list --namespaced -o name   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n trident
```

None of the left over items could be deleted even with --force so I edited them and removed their finalizer and they vanished.

I then, one everything was removed.  I ran the install again and brought everything back up except I removed the spindle CSI and only used the ssd CSI point at "Storage Pool 2" on the QNAP which is (2) 2TB SSDs in RAID1 configuration.  (Storage Pool 1 is (2) 12TB spinning SATA drives in RAID1)

The TridentBackendConfig

```
---
apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-qts # Required. Name your backend in Kubernetes.
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-iscsi #Required. Support 'qnap-nas'(latest) or 'qnap-iscsi'
  backendName: qts # Required. Name your backend in QNAP CSI.
    #  networkInterfaces: [""] # Optional. Your adapter name or leave it empty.
  credentials:
    name: backend-qts-secret # Required. Enter the secret name set in metadata.name.
  debugTraceFlags:
    method: true
  storage: # Required. Define one or more virtual pools.
    - serviceLevel: "Storage Pool 2" # Required. Name your virtual pool.
      labels: # Required. Define custom labels for your virtual pool.
        performance: ssd
      features: # Optional. Define features for your virtual pool.
        tiering: Enable
#    - serviceLevel: "Storage Pool 2"
#      labels:
#        performance: 25g-ssd
#      features:
#        tiering: Enable
#        ssdCache: "true"
#        raidLevel: "1"
```

The qnap-ssd StorageClass definition

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-ssd # Required. Name your storageclass.
provisioner: csi.trident.qnap.io
parameters:
  selector: "performance=ssd" # Required. Corresponds to the labels in the virtual pool.
  fsType: "ext4" # Optional. You can choose to enter ext4 (default), xfs, or ext3.
allowVolumeExpansion: true
```

The test PVC creation yaml.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
  annotations: # Required. Define features for your volume.
    trident.qnap.io/Threshold: "90"
    trident.qnap.io/ThinAllocate: "true"
spec:
  accessModes:
    - ReadWriteOnce # Required. iSCSI: ReadWriteOnce, Samba: ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Required. Specify your resource size.
  storageClassName: qnap-ssd # Required. Corresponds to the StorageClass name.
```

The error I'm getting says there is no storage pool to fulfill the request, but it's there.    

I'm seeing the user I created authenticate in the QNAP logs and I provided the permissions.   I'm at a loss.

The exact error I get when trying to provision the test pvc and then describe it is as follows.   I'm unclear why it says there is no Storage Pool available. 

```
$ k describe pvc pvc1
Name:          pvc1
Namespace:     default
StorageClass:  qnap-ssd
Status:        Pending
Volume:
Labels:        <none>
Annotations:   trident.qnap.io/ThinAllocate: true
               trident.qnap.io/Threshold: 90
               volume.beta.kubernetes.io/storage-provisioner: csi.trident.qnap.io
               volume.kubernetes.io/storage-provisioner: csi.trident.qnap.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age               From                                                                                         Message
  ----     ------                ----              ----                                                                                         -------
  Normal   Provisioning          3s (x2 over 14s)  csi.trident.qnap.io_trident-controller-fc5859d6b-ddl4x_b7fdebe9-46ac-4a8c-afce-e6841455e9bd  External provisioner is provisioning volume for claim "default/pvc1"
  Normal   ExternalProvisioning  2s (x2 over 14s)  persistentvolume-controller                                                                  Waiting for a volume to be created either by the external provisioner 'csi.trident.qnap.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Warning  ProvisioningFailed    0s (x2 over 11s)  csi.trident.qnap.io_trident-controller-fc5859d6b-ddl4x_b7fdebe9-46ac-4a8c-afce-e6841455e9bd  failed to provision volume with StorageClass "qnap-ssd": rpc error: code = Unknown desc = encountered error(s) in creating the volume: [Failed to create volume pvc-dc4a6f91-68f6-49bd-899a-8bd851553d90 on storage pool qts-Storage Pool 2 from backend qts: backend cannot satisfy create request for volume trident-pvc-dc4a6f91-68f6-49bd-899a-8bd851553d90: (backend has no physical pools that can satisfy request)]
```
